package MVC.Vista.Usuarios;

import MVC.Controlador.Ctrl_usuario;
import dataContext.Messages;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import MVC.modelo.Usuario;
import java.awt.event.ActionEvent;

public class GestionarUsers extends javax.swing.JInternalFrame {

    public int idUsuario;
    Messages datacontex = new Messages();

    public GestionarUsers() {
        initComponents();
        this.setSize(new Dimension(1200, 600));
        this.setTitle("LISTA DE USUARIO");
        this.LoadListUser();
        this.unShowSaveChange();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDispone = new javax.swing.JButton();
        GESTIONAR_USUARIO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneListUser = new javax.swing.JScrollPane();
        jtListUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        NOMBRE = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        USUARIO = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        CONTRASEÑA = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        TIPO_USUARIO = new javax.swing.JLabel();
        txtTipoUser = new javax.swing.JTextField();
        panelListUser = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDelet = new javax.swing.JButton();
        newUser = new javax.swing.JLabel();
        deletUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDispone.setBackground(new java.awt.Color(0, 0, 0));
        btnDispone.setForeground(new java.awt.Color(0, 0, 0));
        btnDispone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        btnDispone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponeActionPerformed(evt);
            }
        });
        getContentPane().add(btnDispone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 5, 40, 40));

        GESTIONAR_USUARIO.setBackground(new java.awt.Color(0, 0, 0));
        GESTIONAR_USUARIO.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        GESTIONAR_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        GESTIONAR_USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GESTIONAR_USUARIO.setText("ACCESO A DPAGE");
        GESTIONAR_USUARIO.setOpaque(true);
        getContentPane().add(GESTIONAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 1200, 40));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneListUser.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPaneListUser.setForeground(new java.awt.Color(255, 255, 255));

        jtListUser.setBackground(new java.awt.Color(0, 0, 0));
        jtListUser.setForeground(new java.awt.Color(255, 255, 255));
        jtListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListUser.setGridColor(new java.awt.Color(51, 0, 204));
        jtListUser.setRowHeight(32);
        jScrollPaneListUser.setViewportView(jtListUser);

        jPanel1.add(jScrollPaneListUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 290));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 310));

        panelForm.setBackground(new java.awt.Color(255, 255, 255));
        panelForm.setForeground(new java.awt.Color(255, 255, 255));
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOMBRE.setBackground(new java.awt.Color(255, 255, 255));
        NOMBRE.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(0, 153, 255));
        NOMBRE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NOMBRE.setText("NOMBRE(S)");
        NOMBRE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        txtNombre.setBackground(new java.awt.Color(255, 153, 51));
        txtNombre.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setOpaque(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelForm.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 30));

        APELLIDO.setBackground(new java.awt.Color(255, 255, 255));
        APELLIDO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        APELLIDO.setForeground(new java.awt.Color(0, 153, 255));
        APELLIDO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        APELLIDO.setText("APELLIDOS");
        APELLIDO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 20));

        txtApellido.setBackground(new java.awt.Color(255, 153, 51));
        txtApellido.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        panelForm.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 230, 30));

        USUARIO.setBackground(new java.awt.Color(255, 255, 255));
        USUARIO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(0, 153, 255));
        USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        USUARIO.setText("USUARIO");
        USUARIO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 153, 51));
        txtUsuario.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelForm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 230, 30));

        CONTRASEÑA.setBackground(new java.awt.Color(255, 255, 255));
        CONTRASEÑA.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        CONTRASEÑA.setForeground(new java.awt.Color(0, 153, 255));
        CONTRASEÑA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        CONTRASEÑA.setText("CONTRASEÑA");
        CONTRASEÑA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 20));

        txtContraseña.setBackground(new java.awt.Color(255, 153, 51));
        txtContraseña.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        panelForm.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 230, 30));

        TELEFONO.setBackground(new java.awt.Color(255, 255, 255));
        TELEFONO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        TELEFONO.setForeground(new java.awt.Color(0, 153, 255));
        TELEFONO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TELEFONO.setText("TELEFONO");
        TELEFONO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        txtTelefono.setBackground(new java.awt.Color(255, 153, 51));
        txtTelefono.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        panelForm.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, 30));

        TIPO_USUARIO.setBackground(new java.awt.Color(255, 255, 255));
        TIPO_USUARIO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        TIPO_USUARIO.setForeground(new java.awt.Color(0, 153, 255));
        TIPO_USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TIPO_USUARIO.setText("ESTADO");
        TIPO_USUARIO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(TIPO_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 20));

        txtTipoUser.setBackground(new java.awt.Color(255, 153, 51));
        txtTipoUser.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtTipoUser.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoUserActionPerformed(evt);
            }
        });
        panelForm.add(txtTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 230, 30));

        getContentPane().add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 560, -1));

        panelListUser.setBackground(new java.awt.Color(0, 0, 0));
        panelListUser.setForeground(new java.awt.Color(255, 255, 255));
        panelListUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(19, 167, 14));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editUser_1.png"))); // NOI18N
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setDefaultCapable(false);
        btnSave.setFocusPainted(false);
        btnSave.setFocusable(false);
        btnSave.setRequestFocusEnabled(false);
        btnSave.setVerifyInputWhenFocusTarget(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelListUser.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 5, 110, 110));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addUser_1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setVerifyInputWhenFocusTarget(false);
        panelListUser.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 5, 110, 110));

        btnDelet.setBackground(new java.awt.Color(255, 255, 255));
        btnDelet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelet.setForeground(new java.awt.Color(255, 255, 255));
        btnDelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminarusuario1.png"))); // NOI18N
        btnDelet.setBorderPainted(false);
        btnDelet.setContentAreaFilled(false);
        btnDelet.setDefaultCapable(false);
        btnDelet.setFocusPainted(false);
        btnDelet.setFocusable(false);
        btnDelet.setRequestFocusEnabled(false);
        btnDelet.setVerifyInputWhenFocusTarget(false);
        btnDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletActionPerformed(evt);
            }
        });
        panelListUser.add(btnDelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 5, 110, 110));

        newUser.setBackground(new java.awt.Color(0, 0, 0));
        newUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newUser.setForeground(new java.awt.Color(255, 255, 255));
        newUser.setText("NUEVO USUARIO");
        panelListUser.add(newUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        deletUser.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deletUser.setForeground(new java.awt.Color(255, 255, 255));
        deletUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletUser.setText("ELIMINAR USUARIO");
        panelListUser.add(deletUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GUARDAR CAMBIOS");
        panelListUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        getContentPane().add(panelListUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 65, 560, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/hola1200X400.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 1200, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtUsuarioActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtTelefonoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTipoUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtTipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoUserActionPerformed

    private void btnDeletActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDeletActionPerformed
        if (!txtNombre.getText().isEmpty()
                || !txtApellido.getText().isEmpty()
                || !txtUsuario.getText().isEmpty()
                || !txtContraseña.getText().isEmpty()
                || !txtTelefono.getText().isEmpty()) {
            Usuario usuario = new Usuario();
            Ctrl_usuario ctrl_usuario = new Ctrl_usuario();
            usuario.setNombre(txtNombre.getText().trim());
            usuario.setApellido(txtApellido.getText().trim());
            usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setPassword(txtContraseña.getText().trim());
            usuario.setTelefono(txtTelefono.getText().trim());
            usuario.setEstado(Integer.parseInt(txtTipoUser.getText().trim()));
            if (!ctrl_usuario.DeletUser(idUsuario)) {
                limpiar();
                unShowSaveChange();
                datacontex.successfullDeleted();
                LoadListUser();
            }
        } else {
            datacontex.intenteNuevemante();
        }
    }//GEN-LAST:event_btnDeletActionPerformed

    private void btnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!txtNombre.getText().isEmpty()
                || !txtApellido.getText().isEmpty()
                || !txtUsuario.getText().isEmpty()
                || !txtContraseña.getText().isEmpty()
                || !txtTelefono.getText().isEmpty()) {
            Usuario usuario = new Usuario();
            Ctrl_usuario ctrlUsuario = new Ctrl_usuario();
            usuario.setNombre(txtNombre.getText().trim());
            usuario.setApellido(txtApellido.getText().trim());
            usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setPassword(txtContraseña.getText().trim());
            usuario.setTelefono(txtTelefono.getText().trim());
            usuario.setEstado(Integer.parseInt(txtTipoUser.getText().trim()));

            if (ctrlUsuario.updateUser(usuario, idUsuario)) {
                limpiar();
                datacontex.successfullSave();
                LoadListUser();
            } else {
                datacontex.errorToUpdate();
            }
        } else {
            datacontex.userDataIncorrect();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDisponeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDisponeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnDisponeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JLabel GESTIONAR_USUARIO;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel TELEFONO;
    private javax.swing.JLabel TIPO_USUARIO;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JButton btnDelet;
    private javax.swing.JButton btnDispone;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel deletUser;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPaneListUser;
    public static javax.swing.JTable jtListUser;
    private javax.swing.JLabel newUser;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelListUser;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoUser;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void LoadListUser() {
        Connection cn = conexion.Conexion.conectar();
        DefaultTableModel tblModel = new DefaultTableModel();
        String sql = "SELECT * FROM tb_usuario;";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            GestionarUsers.jtListUser = new JTable(tblModel);
            GestionarUsers.jScrollPaneListUser.setViewportView(GestionarUsers.jtListUser);
            tblModel.addColumn("idUsuario");
            tblModel.addColumn("nombre");
            tblModel.addColumn("apellido");
            tblModel.addColumn("usuario");
            tblModel.addColumn("password");
            tblModel.addColumn("telefono");
            tblModel.addColumn("estado");
            System.out.println(rs);
            while (rs.next()) {
                Object fila[] = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                tblModel.addRow(fila);
                System.out.println(fila);
                //JOptionPane.showMessageDialog(null, fila[1]);
            }
            cn.close();
            GestionarUsers.jtListUser.removeColumn(jtListUser.getColumnModel().getColumn(0));
            GestionarUsers.jtListUser.removeColumn(jtListUser.getColumnModel().getColumn(5));
            GestionarUsers.jtListUser.setBackground(new java.awt.Color(51, 0, 204));
            GestionarUsers.jtListUser.setRowHeight(32);
            GestionarUsers.jScrollPaneListUser.setViewportView(jtListUser);
            jtListUser.setBackground(new java.awt.Color(235, 235, 192));
        } catch (SQLException e) {
        }
        jtListUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                btnDelet.setEnabled(true);
                btnSave.setEnabled(true);
                int fila_point = jtListUser.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idUsuario = (int) tblModel.getValueAt(fila_point, columna_point);
                    // int dataT = (int) tblModel.getValueAt(0, 0);
                    sendUserSelect(idUsuario);
                    //  System.out.println("la dataT ES: "+dataT);
//                    if (columna_point ==dataT) {
//                    JOptionPane.showMessageDialog(null, "PULSASRE LA FILA 1");
//                    }
//                    else {
//                        JOptionPane.showMessageDialog(null, "NO PULSASRE LA FILA 1");
//                            }
                } else {
                }
            }
        });
    }

    private void sendUserSelect(int idUsuario) {
        try {
            Connection cn = conexion.Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM tb_usuario where idUsuario = '" + idUsuario + "'");
            ResultSet rs = pst.executeQuery();
            System.out.println(rs);

            if (rs.next()) {
                txtNombre.setText(rs.getString("nombre"));
                txtApellido.setText(rs.getString("apellido"));
                txtUsuario.setText(rs.getString("usuario"));
                txtContraseña.setText(rs.getString("password"));
                txtTelefono.setText(rs.getString("telefono"));
                txtTipoUser.setText(rs.getString("estado"));
            }
            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL SELECCIONAR EL REGISTRO: " + e);
        }
    }

    private void unShowSaveChange() {
        btnSave.setEnabled(false);
        btnDelet.setEnabled(false);

    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtTelefono.setText("");
        txtTipoUser.setText("");
    }
}
