package Vista.Usuarios;

import Controlador.Ctrl_usuario;
import static Vista.Categoria.InterGestionarCategoria.tb_categorias;
import dataContext.Messages;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

public class GestionarUsers extends javax.swing.JInternalFrame {

    public int idUsuario;
    Messages datacontex = new Messages();

    public GestionarUsers() {
        initComponents();
        this.setSize(new Dimension(600, 400));
        this.setTitle("LISTA DE USUARIO");
        this.LoadListUser();
        this.unShowSaveChange();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        GESTIONAR_USUARIO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneListUser = new javax.swing.JScrollPane();
        jtListUser = new javax.swing.JTable();
        panelListUser = new javax.swing.JPanel();
        btnDelet = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        panelForm = new javax.swing.JPanel();
        NOMBRE = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        USUARIO = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        CONTRASEÑA = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        TIPO_USUARIO = new javax.swing.JLabel();
        txtTipoUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 40));

        GESTIONAR_USUARIO.setBackground(new java.awt.Color(0, 0, 0));
        GESTIONAR_USUARIO.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        GESTIONAR_USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        GESTIONAR_USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GESTIONAR_USUARIO.setText("ACCESO A DPAGE");
        GESTIONAR_USUARIO.setOpaque(true);
        jPanel1.add(GESTIONAR_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtListUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneListUser.setViewportView(jtListUser);

        jPanel2.add(jScrollPaneListUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 80));

        panelListUser.setBackground(new java.awt.Color(255, 255, 255));
        panelListUser.setForeground(new java.awt.Color(255, 255, 255));
        panelListUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelet.setBackground(new java.awt.Color(255, 0, 0));
        btnDelet.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelet.setForeground(new java.awt.Color(0, 0, 0));
        btnDelet.setText("ELIMINAR");
        btnDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletActionPerformed(evt);
            }
        });
        panelListUser.add(btnDelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 30));

        btnEdit.setBackground(new java.awt.Color(255, 204, 0));
        btnEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("CAMBIAR DATOS");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelListUser.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 170, 30));

        btnSave.setBackground(new java.awt.Color(19, 167, 14));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("GUARDAR CAMBIOS");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelListUser.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 170, 30));

        jPanel1.add(panelListUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 580, 50));

        panelForm.setBackground(new java.awt.Color(255, 255, 255));
        panelForm.setForeground(new java.awt.Color(255, 255, 255));
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOMBRE.setBackground(new java.awt.Color(255, 255, 255));
        NOMBRE.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(0, 153, 255));
        NOMBRE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NOMBRE.setText("NOMBRE(S)");
        NOMBRE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 20));

        txtNombre.setBackground(new java.awt.Color(255, 153, 51));
        txtNombre.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setOpaque(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelForm.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 30));

        APELLIDO.setBackground(new java.awt.Color(255, 255, 255));
        APELLIDO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        APELLIDO.setForeground(new java.awt.Color(0, 153, 255));
        APELLIDO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        APELLIDO.setText("APELLIDOS");
        APELLIDO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 20));

        txtApellido.setBackground(new java.awt.Color(255, 153, 51));
        txtApellido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        panelForm.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 250, 30));

        USUARIO.setBackground(new java.awt.Color(255, 255, 255));
        USUARIO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(0, 153, 255));
        USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        USUARIO.setText("USUARIO");
        USUARIO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        txtUsuario.setBackground(new java.awt.Color(255, 153, 51));
        txtUsuario.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelForm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 30));

        CONTRASEÑA.setBackground(new java.awt.Color(255, 255, 255));
        CONTRASEÑA.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        CONTRASEÑA.setForeground(new java.awt.Color(0, 153, 255));
        CONTRASEÑA.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        CONTRASEÑA.setText("CONTRASEÑA");
        CONTRASEÑA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 20));

        txtContraseña.setBackground(new java.awt.Color(255, 153, 51));
        txtContraseña.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        panelForm.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 250, 30));

        TELEFONO.setBackground(new java.awt.Color(255, 255, 255));
        TELEFONO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        TELEFONO.setForeground(new java.awt.Color(0, 153, 255));
        TELEFONO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TELEFONO.setText("TELEFONO");
        TELEFONO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        txtTelefono.setBackground(new java.awt.Color(255, 153, 51));
        txtTelefono.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        panelForm.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 250, 30));

        TIPO_USUARIO.setBackground(new java.awt.Color(255, 255, 255));
        TIPO_USUARIO.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        TIPO_USUARIO.setForeground(new java.awt.Color(0, 153, 255));
        TIPO_USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        TIPO_USUARIO.setText("ESTADO");
        TIPO_USUARIO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelForm.add(TIPO_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 20));

        txtTipoUser.setBackground(new java.awt.Color(255, 153, 51));
        txtTipoUser.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txtTipoUser.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoUserActionPerformed(evt);
            }
        });
        panelForm.add(txtTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 250, 30));

        jPanel1.add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 580, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoForm400-600.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoUserActionPerformed

    private void btnDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!txtNombre.getText().isEmpty()
                || !txtApellido.getText().isEmpty()
                || !txtUsuario.getText().isEmpty()
                || !txtContraseña.getText().isEmpty()
                || !txtTelefono.getText().isEmpty()) {
            Usuario usuario = new Usuario();
            Ctrl_usuario ctrlUsuario = new Ctrl_usuario();
            usuario.setNombre(txtNombre.getText().trim());
            usuario.setApellido(txtApellido.getText().trim());
            usuario.setUsuario(txtUsuario.getText().trim());
            usuario.setPassword(txtContraseña.getText().trim());
            usuario.setTelefono(txtTelefono.getText().trim());
            usuario.setEstado(Integer.parseInt(txtTipoUser.getText().trim()));
            
            if (ctrlUsuario.updateUser(usuario, idUsuario)) {
                datacontex.successfullSave();
                System.out.println(usuario);
                System.out.println(idUsuario);
                System.out.println(txtTelefono);
            } else {
                datacontex.errorToUpdate();
            }
        } else {
            datacontex.userDataIncorrect();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        btnSave.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JLabel GESTIONAR_USUARIO;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel TELEFONO;
    private javax.swing.JLabel TIPO_USUARIO;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JButton btnDelet;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPaneListUser;
    public static javax.swing.JTable jtListUser;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelListUser;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoUser;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void LoadListUser() {
        Connection cn = conexion.Conexion.conectar();
        DefaultTableModel tblModel = new DefaultTableModel();
        String sql = "SELECT nombre,apellido,usuario,password,telefono,estado  FROM tb_usuario;";
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            GestionarUsers.jtListUser = new JTable(tblModel);
            GestionarUsers.jScrollPaneListUser.setViewportView(GestionarUsers.jtListUser);
            //tblModel.addColumn("idUsuario");
            tblModel.addColumn("nombre");
            tblModel.addColumn("apellido");
            tblModel.addColumn("usuario");
            tblModel.addColumn("password");
            tblModel.addColumn("telefono");
            tblModel.addColumn("estado");
            System.out.println(rs);
            while (rs.next()) {
                Object fila[] = new Object[6];
                for (int i = 0; i < 6; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                tblModel.addRow(fila);
                System.out.println(fila);
                //   JOptionPane.showMessageDialog(null, fila[1]);
            }
            cn.close();
        } catch (SQLException e) {
        }
        jtListUser.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jtListUser.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idUsuario = (int) tblModel.getValueAt(fila_point, columna_point);
                    sendUserSelect(idUsuario);
                } else {
                }
            }
        });
    }

    private void sendUserSelect(int idUsuario) {
        try {
            Connection cn = conexion.Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM tb_usuario where idUsuario = '" + idUsuario + "'");
            ResultSet rs = pst.executeQuery();
            System.out.println(rs);

            if (rs.next()) {
                txtNombre.setText(rs.getString("nombre"));
                txtApellido.setText(rs.getString("apellido"));
                txtUsuario.setText(rs.getString("usuario"));
                txtContraseña.setText(rs.getString("password"));
                txtTelefono.setText(rs.getString("telefono"));
                txtTipoUser.setText(rs.getString("estado"));
            }
            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL SELECCIONAR EL REGISTRO: " + e);
        }

    }

    private void unShowSaveChange() {
        btnSave.setVisible(false);

    }
}
