package Vista.Usuarios;

import Controlador.Ctrl_usuario;
import dataContext.Messages;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class newUser extends javax.swing.JInternalFrame {

    Messages dataContext = new Messages();

    public newUser() {
        initComponents();
        this.setSize(new Dimension(600, 400));
        this.setTitle("NUEVO USUARIO");
        //this.validationPhone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NOMBRE = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        USUARIO = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        TELEFONO = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCancel.setBackground(new java.awt.Color(0, 0, 0));
        txtCancel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtCancel.setForeground(new java.awt.Color(255, 255, 255));
        txtCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });
        getContentPane().add(txtCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUEVO USUARIO");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NOMBRE.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(0, 0, 0));
        NOMBRE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NOMBRE.setText("NOMBRE: ");
        NOMBRE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 35));

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 51));
        txtNombre.setAlignmentX(0.0F);
        txtNombre.setAlignmentY(0.0F);
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombre.setMargin(new java.awt.Insets(10, 0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 300, 35));

        APELLIDO.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        APELLIDO.setForeground(new java.awt.Color(0, 0, 0));
        APELLIDO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        APELLIDO.setText("APELLIDOS: ");
        APELLIDO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 160, 35));

        txtApellido.setBackground(new java.awt.Color(0, 0, 0));
        txtApellido.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 51));
        txtApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 55, 300, 35));

        USUARIO.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(0, 0, 0));
        USUARIO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        USUARIO.setText("USUARIO: ");
        USUARIO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 160, 35));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 51));
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 300, 35));

        PASSWORD.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(0, 0, 0));
        PASSWORD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PASSWORD.setText("PASSWORD: ");
        PASSWORD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 145, 160, 35));

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 51));
        txtPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 145, 300, 35));

        TELEFONO.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        TELEFONO.setForeground(new java.awt.Color(0, 0, 0));
        TELEFONO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TELEFONO.setText("TELEFONO: ");
        TELEFONO.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 35));

        txtTelefono.setBackground(new java.awt.Color(0, 0, 0));
        txtTelefono.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 51));
        txtTelefono.setToolTipText("");
        txtTelefono.setActionCommand("<Not Set>");
        txtTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 300, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 500, 235));

        btnSave.setBackground(new java.awt.Color(51, 255, 51));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 500, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoForm400-600.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Ctrl_usuario ctrl_usuario = new Ctrl_usuario();
        Usuario usuario = new Usuario();

        //Validation de tex
        if (txtNombre.getText().equals("")
                || txtApellido.getText().equals("")
                || txtUsuario.getText().equals("")
                || txtPassword.getText().equals("")
                || txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "SE TIENE CONFIGURAR LA VALIDACION");
        } else {
            if (!ctrl_usuario.comprobarExitencia(txtUsuario.getText().trim())) {
                usuario.setIdUsuario(0);
                usuario.setNombre(txtNombre.getText().trim());
                usuario.setApellido(txtApellido.getText().trim());
                usuario.setUsuario(txtUsuario.getText().trim());
                usuario.setPassword(txtPassword.getText().trim());
                usuario.setTelefono(txtTelefono.getText().trim());
                usuario.setEstado(1);
                System.out.println(usuario);
                if (ctrl_usuario.saveUser(usuario)) {
                    dataContext.successfullSave();
                    this.limpiar();
                } else {
                    dataContext.errorToSave();
                }

            } else {
                dataContext.userDuplicated();
            }

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_txtCancelActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;
        if (!numero) {
            //PERMITE SOLAMENTE 
            evt.consume();
        }
        //FUNCION PARA OBTENER UN RANGO DE TEXT
        if (txtTelefono.getText().trim().length() == 11) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JLabel TELEFONO;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JButton txtCancel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
       txtNombre.setText("");
       txtApellido.setText("");
       txtUsuario.setText("");
       txtPassword.setText("");
       txtTelefono.setText("");
       
    }

}
