package Vista.Index;

import Vista.Categoria.InterGestionarCategoria;
import Vista.Categoria.newCategoria;
import Vista.Producto.newProduct;
import Vista.Usuarios.GestionarUsers;
import Vista.Usuarios.newUser;
import java.awt.Dimension;
import javax.swing.JDesktopPane;

public class FrmMenu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_new;
    

    public FrmMenu() { 
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        this.setLocationRelativeTo(null);
        this.setTitle("SISTEMA DE VENTAS");
        
        this.setLayout(null);
        jDesktopPane_new = new JDesktopPane();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        this.jDesktopPane_new.setBounds(0,0 ,ancho,  (alto -110));
        this.add(jDesktopPane_new);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mn_usuario = new javax.swing.JMenu();
        mi_nuevoUsuario = new javax.swing.JMenuItem();
        mi_gestionarUsuario = new javax.swing.JMenuItem();
        mn_producto = new javax.swing.JMenu();
        mi_nuevoProducto = new javax.swing.JMenuItem();
        mi_gestionarProductos = new javax.swing.JMenuItem();
        mi_actualizarProductos = new javax.swing.JMenuItem();
        mn_cliente = new javax.swing.JMenu();
        mi_nuevoCliente = new javax.swing.JMenuItem();
        mi_gestionarClientes = new javax.swing.JMenuItem();
        mn_categoria = new javax.swing.JMenu();
        mi_nuevaCategoria = new javax.swing.JMenuItem();
        mi_gestionarCategorias = new javax.swing.JMenuItem();
        mn_facturar = new javax.swing.JMenu();
        mi_nuevaVenta = new javax.swing.JMenuItem();
        mi_gestionarVentas = new javax.swing.JMenuItem();
        mn_reporte = new javax.swing.JMenu();
        mi_reporteClientes = new javax.swing.JMenuItem();
        mi_reporteCategorias = new javax.swing.JMenuItem();
        mi_reporteProductos = new javax.swing.JMenuItem();
        mi_reporteVentas = new javax.swing.JMenuItem();
        mn_historial = new javax.swing.JMenu();
        mi_verHistorial = new javax.swing.JMenuItem();
        mn_cerrarSesion = new javax.swing.JMenu();
        mi_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N
        mn_usuario.setText("USUARIOS");
        mn_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_usuario.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_usuario.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-cliente.png"))); // NOI18N
        mi_nuevoUsuario.setText("Nuevo usuario");
        mi_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nuevoUsuarioActionPerformed(evt);
            }
        });
        mn_usuario.add(mi_nuevoUsuario);

        mi_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/configuraciones.png"))); // NOI18N
        mi_gestionarUsuario.setText("Gestionar usuarios");
        mi_gestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gestionarUsuarioActionPerformed(evt);
            }
        });
        mn_usuario.add(mi_gestionarUsuario);

        jMenuBar1.add(mn_usuario);

        mn_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        mn_producto.setText("PRODUCTOS");
        mn_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_producto.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_producto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_producto.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-producto.png"))); // NOI18N
        mi_nuevoProducto.setText("Nuevo Producto");
        mi_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_newProduct(evt);
            }
        });
        mn_producto.add(mi_nuevoProducto);

        mi_gestionarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        mi_gestionarProductos.setText("Gestionar Productos");
        mn_producto.add(mi_gestionarProductos);

        mi_actualizarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        mi_actualizarProductos.setText("Actualizar Almacen");
        mn_producto.add(mi_actualizarProductos);

        jMenuBar1.add(mn_producto);

        mn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cliente.png"))); // NOI18N
        mn_cliente.setText("CLIENTES");
        mn_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_cliente.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_cliente.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-cliente.png"))); // NOI18N
        mi_nuevoCliente.setText("Nuevo Cliente");
        mn_cliente.add(mi_nuevoCliente);

        mi_gestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cliente.png"))); // NOI18N
        mi_gestionarClientes.setText("Gestionar Clientes");
        mi_gestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gestionarClientesActionPerformed(evt);
            }
        });
        mn_cliente.add(mi_gestionarClientes);

        jMenuBar1.add(mn_cliente);

        mn_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/categorias.png"))); // NOI18N
        mn_categoria.setText("CATEGORIA");
        mn_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_categoria.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_categoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_categoria.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_nuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        mi_nuevaCategoria.setText("Nueva Categoria");
        mi_nuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nuevaCategoriaActionPerformed(evt);
            }
        });
        mn_categoria.add(mi_nuevaCategoria);

        mi_gestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/categorias.png"))); // NOI18N
        mi_gestionarCategorias.setText("Gestionar Categoria");
        mi_gestionarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gestionarCategoriasActionPerformed(evt);
            }
        });
        mn_categoria.add(mi_gestionarCategorias);

        jMenuBar1.add(mn_categoria);

        mn_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito.png"))); // NOI18N
        mn_facturar.setText("FACTURAR");
        mn_facturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_facturar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_facturar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_facturar.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/anadir.png"))); // NOI18N
        mi_nuevaVenta.setText("Nueva Venta");
        mn_facturar.add(mi_nuevaVenta);

        mi_gestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/configuraciones.png"))); // NOI18N
        mi_gestionarVentas.setText("Gestionar Ventas");
        mi_gestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_gestionarVentasActionPerformed(evt);
            }
        });
        mn_facturar.add(mi_gestionarVentas);

        jMenuBar1.add(mn_facturar);

        mn_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reporte1.png"))); // NOI18N
        mn_reporte.setText("REPORTES");
        mn_reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_reporte.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_reporte.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_reporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportes.png"))); // NOI18N
        mi_reporteClientes.setText("Reportes Clientes");
        mn_reporte.add(mi_reporteClientes);

        mi_reporteCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportes.png"))); // NOI18N
        mi_reporteCategorias.setText("Reportes Categoria");
        mn_reporte.add(mi_reporteCategorias);

        mi_reporteProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportes.png"))); // NOI18N
        mi_reporteProductos.setText("Reportes Productos");
        mn_reporte.add(mi_reporteProductos);

        mi_reporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportes.png"))); // NOI18N
        mi_reporteVentas.setText("Reportes Ventas");
        mn_reporte.add(mi_reporteVentas);

        jMenuBar1.add(mn_reporte);

        mn_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/historial1.png"))); // NOI18N
        mn_historial.setText("HISTORIAL");
        mn_historial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_historial.setFont(new java.awt.Font("Franklin Gothic Book", 1, 16)); // NOI18N
        mn_historial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_historial.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/historial1.png"))); // NOI18N
        mi_verHistorial.setText("Ver Historial");
        mn_historial.add(mi_verHistorial);

        jMenuBar1.add(mn_historial);

        mn_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion.png"))); // NOI18N
        mn_cerrarSesion.setText("CERRAR SESION");
        mn_cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mn_cerrarSesion.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        mn_cerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mn_cerrarSesion.setMinimumSize(new java.awt.Dimension(120, 80));
        mn_cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 60));

        mi_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-sesion.png"))); // NOI18N
        mi_cerrarSesion.setText("Cerrar Sesion");
        mi_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cerrarSesionActionPerformed(evt);
            }
        });
        mn_cerrarSesion.add(mi_cerrarSesion);

        jMenuBar1.add(mn_cerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_gestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gestionarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_gestionarClientesActionPerformed

    private void mi_gestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gestionarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_gestionarVentasActionPerformed

    private void mi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_cerrarSesionActionPerformed

    private void mi_nuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nuevaCategoriaActionPerformed
        // funcion para lanzar el interFrame de INTERCATEGORIA
        newCategoria interCategoria = new newCategoria();
        jDesktopPane_new.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_mi_nuevaCategoriaActionPerformed

    private void mi_gestionarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gestionarCategoriasActionPerformed
        // funcion para lanzar el InterFrame de GESTIONAR CATEGORIA
        InterGestionarCategoria intergestiCate = new InterGestionarCategoria();
        jDesktopPane_new.add(intergestiCate);
        intergestiCate.setVisible(true);                
    }//GEN-LAST:event_mi_gestionarCategoriasActionPerformed

    private void mi_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nuevoUsuarioActionPerformed
        newUser formNewUser1 = new newUser();
        jDesktopPane_new.add(formNewUser1);
        formNewUser1.setVisible(true);
        
        
    }//GEN-LAST:event_mi_nuevoUsuarioActionPerformed

    private void mi_newProduct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_newProduct
        newProduct newProduct1 = new newProduct();
        jDesktopPane_new.add(newProduct1);
        newProduct1.setVisible(true);
    }//GEN-LAST:event_mi_newProduct

    private void mi_gestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_gestionarUsuarioActionPerformed
        GestionarUsers viewGestionarUser = new GestionarUsers();
        jDesktopPane_new.add(viewGestionarUser).setBounds(200, 120, 600, 400);
        viewGestionarUser.setVisible(true);
    }//GEN-LAST:event_mi_gestionarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mi_actualizarProductos;
    private javax.swing.JMenuItem mi_cerrarSesion;
    private javax.swing.JMenuItem mi_gestionarCategorias;
    private javax.swing.JMenuItem mi_gestionarClientes;
    private javax.swing.JMenuItem mi_gestionarProductos;
    private javax.swing.JMenuItem mi_gestionarUsuario;
    private javax.swing.JMenuItem mi_gestionarVentas;
    private javax.swing.JMenuItem mi_nuevaCategoria;
    private javax.swing.JMenuItem mi_nuevaVenta;
    private javax.swing.JMenuItem mi_nuevoCliente;
    private javax.swing.JMenuItem mi_nuevoProducto;
    private javax.swing.JMenuItem mi_nuevoUsuario;
    private javax.swing.JMenuItem mi_reporteCategorias;
    private javax.swing.JMenuItem mi_reporteClientes;
    private javax.swing.JMenuItem mi_reporteProductos;
    private javax.swing.JMenuItem mi_reporteVentas;
    private javax.swing.JMenuItem mi_verHistorial;
    private javax.swing.JMenu mn_categoria;
    private javax.swing.JMenu mn_cerrarSesion;
    private javax.swing.JMenu mn_cliente;
    private javax.swing.JMenu mn_facturar;
    private javax.swing.JMenu mn_historial;
    private javax.swing.JMenu mn_producto;
    private javax.swing.JMenu mn_reporte;
    private javax.swing.JMenu mn_usuario;
    // End of variables declaration//GEN-END:variables
}
